tags:
- name: acronyms
  description: acronyms API

paths:
# [GET] acronym
  /acronym:
    get:
      tags:
      - acronyms
      summary: Find All acronyms
      parameters:
      - name: from
        in: query
        description: start position
        type: integer
      - name: limit
        in: query
        description: counts to fetch
        type: integer
      - name: search
        in: query
        description: search string
        type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] acronym
    post:
      tags:
      - acronyms
      summary: Add acronym
      parameters:
      - name: body
        in: body
        description: acronym Data
        required: true
        schema:
          $ref: '#/definitions/acronyms'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] acronym/acronym
  /acronym/{acronym}:
    put:
      tags:
      - acronyms
      summary: Update acronym
      parameters:
      - name: acronym
        in: path
        description: acronym
        required: true
        type: string
      - name: body
        in: body
        description: acronym Data
        required: true
        schema:
          $ref: '#/definitions/acronyms'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] acronym/acronym
    delete:
      tags:
      - acronyms
      summary: Delete acronym
      parameters:
      - name: acronym
        in: path
        description: acronym
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  acronyms:
    type: object
    required:
        - acronym
        - definition
    properties:
      acronym:
        type: string
        description: abbreviation of something
      definition:
        type: string
        description: definition of acronym

schemes:
 - https
 - http
